const utils = {
  names: [
    'Mark', 'Bob', 'John', 'Ann', 'Mary', 'Sarah', 'Nick', 'Sally', 'Rob', 'Alex', 'Stephanie'
  ],
  phrases: [
    'OK',
    'I\'m working!',
    'I\'m fine.',
    'I\'m resting.',
    '\u{1F4A4}',
    'I\'m hungry!',
    'I\'m tired.',
    'I\'m busy...',
    'I\'m happy!',
    'It\'s interesting!',
    'It\'s not interesting.',
    'It\'s boring...',
    'In more detail please.',
    'What\'s new?',
    'Let\'s sing!',
    '\u{1F48B}',
    'Let\'s dance!',
    'It\'s horrible!',
    'It\'s wonderful!',
    'It\'s normal.',
    'What tomorrow?',
    'Why?',
    'What?',
    'Sorry, I\'m totally swamped',
    'What aboute planes?',
    'That\'s for me?',
    'I bought a watermelon!',
    'Birds fly low....',
    'I\'m cool!',
    'You\'re cool',
    '\u{1F60A}',
    '\u{1F911}',
    '\u{1F922}',
    '\u{1F633}',
    '\u{1F97A}',
    '\u{1F621}',
    'I tried to get a job, but it\'s like pulling teeth',
    '\u{1F47D}',
    '\u{1F916}',
    '\u{1F436}',
    '\u{1F43A}',
    '\u{1F98A}',
    'I\'m at home...',
    'Are you alright?',
    'I wracked my brains trying to solve this problem...',
    'Very good!',
    'Well, here we go again!',
    'So what?!,'
  ],
  greetings: [
    'Hi, ', 'Hello, ', 'Good day, ',
  ],
  farewell: [
    'Goodbye, ', 'See you later, ', 'Good luck, ',
  ],
  colors: [
    'black', 'blue', 'green', 'red', 'orange', 'violet', 'brown', 'grey',
  ],
}
module.exports = utils;